# Generated by Django 3.0.3 on 2020-02-17 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annslogsapp', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='text',
            new_name='name',
        ),
    ]
